/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * MaNGOS is a full featured server for World of Warcraft, supporting
 * the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
 *
 * Copyright (C) 2005-2026 MaNGOS <https://www.getmangos.eu>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * World of Warcraft, and all World of Warcraft or Warcraft art, images,
 * and lore are copyrighted by Blizzard Entertainment, Inc.
 */

#ifndef MANGOSSERVER_COMBAT_ARMORREDUCTION_H
#define MANGOSSERVER_COMBAT_ARMORREDUCTION_H

#include "Platform/Define.h"

/**
 * COMBAT ARITHMETIC THAT DOES NOT NEED A UNIT.
 *
 * Decoupling D5b moved these formulas out of Unit and Player verbatim: every `this`
 * read became a parameter of the same type, named after the read it replaced, and
 * nothing else changed -- not a branch, not a clamp, not the order of an addition.
 * The member that used to hold the body is now a forwarder that gathers the reads and
 * calls in here, so the formula has exactly one copy and the combat kernel that
 * follows this campaign can call it without constructing a world.
 *
 * Each function is pinned by golden vectors in src/tests/CombatGoldenVectors.h,
 * generated by a Python transcription of the ORIGINAL body (src/tests/tools/
 * gen_combat_vectors.py). Changing a formula here without regenerating those vectors
 * fails src/tests/CombatLeafTest.cpp, which is the point.
 *
 * This header knows nothing about Unit, Object, Player, Creature, auras, the DBC
 * stores or the session -- src/tests/CheckHeaderReach.cmake enforces that.
 */
namespace Combat
{
    /**
     * @brief Reduces physical damage by the victim's effective armor.
     *
     * Unit::CalcArmorReducedDamage, src/game/Object/UnitDamage.cpp:71-121 at ce20c27db,
     * moved verbatim. The Player-only armour penetration block keeps its guard as
     * `isPlayer`.
     *
     * @param damage The incoming physical damage.
     * @param victimArmor pVictim->GetArmor().
     * @param targetResistanceMod GetTotalAuraModifierByMiscMask(SPELL_AURA_MOD_TARGET_RESISTANCE, SPELL_SCHOOL_MASK_NORMAL).
     * @param isPlayer GetTypeId() == TYPEID_PLAYER.
     * @param attackerLevel getLevel().
     * @param victimLevel pVictim->getLevel().
     * @param armorPenetrationPct ((Player*)this)->GetArmorPenetrationPct(), 0 when the attacker is not a player.
     * @return The reduced damage amount, never below 1.
     */
    uint32 ArmorReducedDamage(uint32 damage, uint32 victimArmor, int32 targetResistanceMod,
                              bool isPlayer, uint32 attackerLevel, uint32 victimLevel,
                              float armorPenetrationPct);
}

#endif // MANGOSSERVER_COMBAT_ARMORREDUCTION_H
