include("${CMAKE_CURRENT_LIST_DIR}/GateGuards.cmake")
gate_require_source_root("Client-map-id gate")

set(ROOTS "${SOURCE_ROOT}/src/game" "${SOURCE_ROOT}/src/modules")
set(SOURCES "")
foreach(ROOT_DIR IN LISTS ROOTS)
    if(NOT IS_DIRECTORY "${ROOT_DIR}")
        message(FATAL_ERROR "Client-map-id gate: missing ${ROOT_DIR}")
    endif()
    file(GLOB_RECURSE FOUND "${ROOT_DIR}/*.cpp" "${ROOT_DIR}/*.h")
    if(NOT FOUND)
        message(FATAL_ERROR "Client-map-id gate: no sources under ${ROOT_DIR} -- gate is inert")
    endif()
    list(APPEND SOURCES ${FOUND})
endforeach()

set(CONSTRUCTIONS 0)
set(STRAYS "")
foreach(FILE_PATH IN LISTS SOURCES)
    file(READ "${FILE_PATH}" CONTENTS)
    string(FIND "${CONTENTS}" "UpdateData" HAS_USE)
    if(HAS_USE EQUAL -1)
        continue()
    endif()
    string(REGEX MATCHALL "UpdateData[ \t\r\n]*[A-Za-z_][A-Za-z0-9_]*[ \t\r\n]*\\(|UpdateData[ \t\r\n]*\\(" OPENS "${CONTENTS}")
    list(LENGTH OPENS OPEN_COUNT)
    math(EXPR CONSTRUCTIONS "${CONSTRUCTIONS} + ${OPEN_COUNT}")
    string(REGEX MATCHALL "UpdateData[ \t\r\n]*[A-Za-z_0-9]*[ \t\r\n]*\\([^)]*GetMapId[ \t\r\n]*\\(" HITS "${CONTENTS}")
    foreach(HIT IN LISTS HITS)
        file(RELATIVE_PATH REL "${SOURCE_ROOT}" "${FILE_PATH}")
        string(REGEX REPLACE "[\r\n\t ]+" " " FLAT "${HIT}")
        list(APPEND STRAYS "${REL}: ${FLAT})")
    endforeach()
endforeach()

if(CONSTRUCTIONS EQUAL 0)
    message(FATAL_ERROR "Client-map-id gate saw no UpdateData construction at all -- gate is inert")
endif()
if(STRAYS)
    string(REPLACE ";" "\n  " PRETTY "${STRAYS}")
    message(FATAL_ERROR
        "An update packet is built from a raw map id:\n  ${PRETTY}\n\n"
        "Build it from WorldObject::GetClientMapId() instead: a passenger's GetMapId() is the\n"
        "vessel's hull map, which the client reads as a world change and crashes on.")
endif()
message(STATUS "client map id: ${CONSTRUCTIONS} UpdateData construction(s), none from a raw GetMapId()")
