include("${CMAKE_CURRENT_LIST_DIR}/GateGuards.cmake")
gate_require_source_root("Blocked-mask gate")

set(ROOTS "${SOURCE_ROOT}/src/game" "${SOURCE_ROOT}/src/modules")
set(SOURCES "")
foreach(ROOT_DIR IN LISTS ROOTS)
    if(NOT IS_DIRECTORY "${ROOT_DIR}")
        message(FATAL_ERROR "Blocked-mask gate: missing ${ROOT_DIR}")
    endif()
    file(GLOB_RECURSE FOUND "${ROOT_DIR}/*.cpp" "${ROOT_DIR}/*.h")
    list(LENGTH FOUND FOUND_COUNT)
    if(FOUND_COUNT EQUAL 0)
        message(FATAL_ERROR "Blocked-mask gate found no sources under ${ROOT_DIR} -- gate is inert")
    endif()
    list(APPEND SOURCES ${FOUND})
endforeach()
list(LENGTH SOURCES SOURCE_COUNT)

set(UNIT_HEADER "${SOURCE_ROOT}/src/game/Object/Unit.h")
file(READ "${UNIT_HEADER}" UNIT_TEXT)
string(FIND "${UNIT_TEXT}" "bool Blocked(UnitState) const = delete;" HAS_GUARD)
if(HAS_GUARD EQUAL -1)
    message(FATAL_ERROR "Blocked-mask gate: Unit.h no longer deletes Blocked(UnitState); a single unit-state constant would bind to Blocked(uint32)")
endif()

set(MEMBER_CALLS 0)
set(STRAYS "")
foreach(FILE_PATH IN LISTS SOURCES)
    file(READ "${FILE_PATH}" CONTENTS)
    string(FIND "${CONTENTS}" "Blocked" HAS_CALL)
    if(HAS_CALL EQUAL -1)
        continue()
    endif()
    if(NOT FILE_PATH STREQUAL UNIT_HEADER)
        string(REGEX MATCHALL "(->|\\.)Blocked[ \t\r\n]*\\(" MEMBER_HITS "${CONTENTS}")
        list(LENGTH MEMBER_HITS MEMBER_HIT_COUNT)
        math(EXPR MEMBER_CALLS "${MEMBER_CALLS} + ${MEMBER_HIT_COUNT}")
    endif()
    string(REGEX MATCHALL "Blocked[ \t\r\n]*\\([^)]*UNIT_STAT_[A-Z_]*" HITS "${CONTENTS}")
    foreach(HIT IN LISTS HITS)
        file(RELATIVE_PATH REL "${SOURCE_ROOT}" "${FILE_PATH}")
        string(REGEX REPLACE "[\r\n\t ]+" " " FLAT "${HIT}")
        list(APPEND STRAYS "${REL}: ${FLAT}")
    endforeach()
endforeach()

if(MEMBER_CALLS EQUAL 0)
    message(FATAL_ERROR "Blocked-mask gate saw no Blocked( call outside Unit.h -- gate is inert")
endif()
if(STRAYS)
    string(REPLACE ";" "\n  " PRETTY "${STRAYS}")
    message(FATAL_ERROR
        "Unit::Blocked called with a unit-state mask:\n  ${PRETTY}\n\n"
        "Blocked takes Motion::Reason bits (Motion::ReasonStunned, Motion::kCannotMoveReasons, ...);\n"
        "a UNIT_STAT_ constant there is read as the reason with the same bit value.")
endif()
message(STATUS "blocked masks: ${MEMBER_CALLS} Blocked( member calls outside Unit.h in ${SOURCE_COUNT} files, none with a UNIT_STAT_ argument")
