#!/usr/bin/env python3
"""Translate the Montgomery kernel's GAS Intel-syntax source into its MASM twin.

One assembly source is the rule (src/shared/Crypto/MontgomeryAsm.S); MSVC cannot
assemble GAS, so this script emits MontgomeryAsm.asm for ml64 from it, with the
WINDOWS_ABI branches selected. The translation is line by line and deliberately
narrow -- the kernel uses a small, fixed vocabulary (the directives below, decimal
immediates, `qword ptr [base + index + disp]` operands, local labels) and anything
outside it is an error rather than a guess. A test regenerates the twin and
compares it with the committed file, so the two cannot drift.

    python3 src/tests/tools/gas2masm.py src/shared/Crypto/MontgomeryAsm.S > src/shared/Crypto/MontgomeryAsm.asm
"""
import re
import sys

KNOWN_MNEMONICS = {
    "push", "pop", "mov", "lea", "and", "or", "xor", "not", "neg", "add", "sub", "sbb", "adc",
    "shl", "shr", "imul", "mulx", "adcx", "adox", "cmp", "jb", "jae", "jnz", "jmp", "jrcxz", "ret",
}


def translate(lines):
    out = ["; Generated by src/tests/tools/gas2masm.py from MontgomeryAsm.S; do not edit by hand.",
           "; The GAS source is the one source; a test checks this twin is current.", ""]
    proc = None
    # #if WINDOWS_ABI / #else / #endif: keep the Windows branch
    stack = []          # each entry: True when the current branch is emitted
    for raw in lines:
        line = raw.rstrip("\n")
        stripped = line.strip()
        if stripped.startswith("#if "):
            cond = stripped[4:].strip()
            if cond == "WINDOWS_ABI":
                stack.append(True)
            elif cond == "!WINDOWS_ABI":
                stack.append(False)
            else:
                raise SystemExit(f"unknown condition: {stripped}")
            continue
        if stripped == "#else":
            stack[-1] = not stack[-1]
            continue
        if stripped == "#endif":
            stack.pop()
            continue
        if stack and not all(stack):
            continue
        # comments
        if stripped.startswith("//"):
            out.append("; " + stripped[2:].strip() if stripped[2:].strip() else ";")
            continue
        if stripped == "":
            out.append("")
            continue
        code, _, comment = stripped.partition("//")
        code = code.strip()
        suffix = ("    ; " + comment.strip()) if comment.strip() else ""
        # directives
        if code.startswith("."):
            if code == ".intel_syntax noprefix":
                continue
            if code == ".text":
                out.append(".code")
                continue
            m = re.match(r"\.balign\s+(\d+)$", code)
            if m:
                out.append(f"        ALIGN {m.group(1)}")
                continue
            m = re.match(r"\.globl\s+(\w+)$", code)
            if m:
                out.append(f"        PUBLIC {m.group(1)}")
                continue
            # local labels: .Lname: -> Lname:
            m = re.match(r"\.L(\w+):$", code)
            if m:
                out.append(f"L{m.group(1)}:")
                continue
            # the MASM unwind directives of the Windows branch pass through as they are
            if re.match(r"\.(pushreg\s+\w+|setframe\s+\w+,\s*\d+|allocstack\s+\d+|endprolog)$", code):
                out.append(f"        {code}")
                continue
            raise SystemExit(f"unhandled directive: {code}")
        # global label -> PROC FRAME (the Windows branch carries the unwind directives)
        m = re.match(r"(\w+):$", code)
        if m:
            if proc:
                raise SystemExit("nested procedure")
            proc = m.group(1)
            out.append(f"{proc} PROC FRAME")
            continue
        # instruction
        parts = code.split(None, 1)
        mnemonic = parts[0]
        if mnemonic not in KNOWN_MNEMONICS:
            raise SystemExit(f"mnemonic outside the kernel's vocabulary: {code}")
        operands = parts[1] if len(parts) > 1 else ""
        # jump targets: .Lname -> Lname
        operands = re.sub(r"\.L(\w+)", r"L\1", operands)
        # hex immediates would need MASM's trailing-h form; the kernel uses none
        if re.search(r"0x[0-9A-Fa-f]+", operands):
            raise SystemExit(f"hex immediate not supported: {code}")
        out.append(f"        {mnemonic} {operands}".rstrip() + suffix)
        if mnemonic == "ret" and proc:
            out.append(f"{proc} ENDP")
            proc = None
    if proc:
        raise SystemExit("procedure without ret")
    out.append("END")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: gas2masm.py MontgomeryAsm.S > MontgomeryAsm.asm")
    with open(sys.argv[1], encoding="utf-8") as f:
        sys.stdout.write(translate(f.readlines()))


if __name__ == "__main__":
    main()
