#!/usr/bin/env python3
"""Generate src/tests/RsaTestKey.h: the throwaway RSA-2048 pair ConnectToTest carries,
completed with its CRT parameters.

The pair in the tree is (n, d) only. Knowing d and e factors n (the classic argument:
d*e - 1 is a multiple of lambda(n), so a random base raised to its odd part reaches a
non-trivial square root of 1 modulo n after a few squarings). From p and q follow
dP, dQ and qInv, which is what a server.secret written by the in-house key generator
carries and what the CRT signing path needs. Deterministic: the bases are tried in order.

python3 src/tests/tools/gen_rsa_test_key.py > src/tests/RsaTestKey.h
"""
import math

N_HEX = (
    "91744218A5AC0134DC2BE63E95AA3F2F3130C1714DB7084E3AC31A170C4FA02B"
    "F9D62E5CB1E444258D852B100395CF7D2DC0088BB7B96DF2B1EDC3BFF0D968F8"
    "D1003D4726DBC79417B001AB37653922BC10FF538B43B186E0071E41653382C5"
    "2FE58D701948AAA8F20D15B62EC4147AE1142AC3A287461D8F8C9D4021369889"
    "FED17806C3662CEC078092D90CBE881343A160C0CD8984094C7D6F18481DE73E"
    "14EB6766D7C9EF88A575B5910C67D62F4071EFB3639EF5A1E7892CF16F6D6D43"
    "F56495769D0683580030F514CB21208360116717C16CCC4B233A11F8CCB3CEBC"
    "D9873C33CFA81ACD619F567403D8839B88CA37FA08392F02439054B88E70E233"
)
D_HEX = (
    "0B8B0F67C756142E6EBEA922145C93711A554534C9B719D8A37F3245DBFB41B9"
    "DBB4ECAEFC8B22015CEED1910EC7C7D4A659D413CA7BD3C6EBE9F39BFAF0360D"
    "7100B4DC3DB039717E43C08E26F2488B8223532FFD205D295804189995FF7584"
    "529DC410BE60EEF2436B586AC1E15BC2B8B41204BE943FB33EDE28E89AFA2B36"
    "C145CA75174805FA0278EC54B545CDFF1D744C63BDC2F568692480D04933E295"
    "E0AFE18D886721843D41B51F491900EB58771749BD032F5B9453484516B26642"
    "A1355D38C1CD98F2E079FC3B66303DB17EEAE5B8A2DAFE605093031EE242C2C2"
    "C84BD028B6E94F3B87C2800FD79D7EFCD5DC40C53853A448DB17393EFDFEFEB9"
)
E = 65537


def hexs(v):
    h = format(v, "X")
    return ("0" + h) if len(h) % 2 else h


def factor(n, e, d):
    k = d * e - 1
    t = 0
    while k % 2 == 0:
        k //= 2
        t += 1
    for g in range(2, 1000):
        y = pow(g, k, n)
        if y in (1, n - 1):
            continue
        for _ in range(t):
            x = pow(y, 2, n)
            if x == 1:
                p = math.gcd(y - 1, n)
                if 1 < p < n:
                    return p
                break
            if x == n - 1:
                break
            y = x
    raise SystemExit("could not factor n from (e, d)")


n = int(N_HEX, 16)
d = int(D_HEX, 16)
p = factor(n, E, d)
q = n // p
if p < q:
    p, q = q, p            # PKCS#1 does not require it, but p > q keeps m2 < q < p for the recombination
assert p * q == n
dP = d % (p - 1)
dQ = d % (q - 1)
qInv = pow(q, -1, p)
assert (E * dP) % (p - 1) == 1 and (E * dQ) % (q - 1) == 1 and (q * qInv) % p == 1

# the CRT signature of a probe equals the plain one
m = int.from_bytes(bytes([0x00] + [0x5A] * 255), "big")
plain = pow(m, d, n)
m1, m2 = pow(m, dP, p), pow(m, dQ, q)
h = (qInv * (m1 - m2)) % p
assert m2 + h * q == plain

print("// Generated by src/tests/tools/gen_rsa_test_key.py; do not edit by hand.")
print("// The throwaway RSA-2048 pair ConnectToTest carries, completed with the CRT parameters")
print("// recovered from (n, e, d). Hex as BN_bn2hex rendered it: whole bytes, uppercase.")
print("#ifndef MANGOS_H_TESTS_RSA_TEST_KEY")
print("#define MANGOS_H_TESTS_RSA_TEST_KEY")
print("")
print("namespace testkey")
print("{")
for name, value in (("kModulus", n), ("kPublicExponent", E), ("kPrivateExponent", d), ("kPrime1", p), ("kPrime2", q), ("kExponent1", dP), ("kExponent2", dQ), ("kCoefficient", qInv)):
    print('    inline const char* %s = "%s";' % (name, hexs(value)))
print("}")
print("")
print("#endif")
