#!/usr/bin/env python3
"""Generate src/shared/Crypto/MontgomeryAsm.S, the assembly tier of the Montgomery kernel.

The listing has five procedures, all x86-64 with BMI2 + ADX, GAS Intel syntax, both
ABIs under WINDOWS_ABI (the MASM twin is produced from the output by gas2masm.py):

  mangos_montmul_adx(z, x, y, m, n0inv, k)   generic k (a positive multiple of 4), looped
  mangos_montmul16_adx / mangos_montmul32_adx(z, x, y, m, n0inv)   the same CIOS, unrolled
  mangos_montsqr16_adx / mangos_montsqr32_adx(z, x, m, n0inv)      a dedicated squaring

Why generated: the unrolled procedures are the generic one with every loop replaced
by straight-line code. Measured on the development machine, the product step -- mulx,
adcx of the accumulator limb, adox of the carry, store -- costs 1.1 TSC ticks in a
straight line and 2.0 inside the generic loop, whose flag-neutral control (jrcxz, lea,
jmp between every four products) is what the carry chains force on a loop. At the two
widths the server uses (the 1024-bit CRT halves, the 2048-bit modulus) the loops are
simply written out; the generic procedure stays for other multiples of four. The
squaring does k(k-1)/2 off-diagonal products (row scanning of the upper triangle),
doubles the sum with one add-with-carry chain, adds the k squares on the diagonal with
another, and reduces in place: k rows of q[i] * m at offset i, each row's carry folded
into the next row's top limb, the last one becoming the word above -- 1.5 k^2 products
instead of 2 k^2. Every procedure ends in the same masked subtraction.

Constant-time discipline as in the generic kernel: no branch, loop count or address
depends on data; the final subtraction is a mask; the frame is erased before return.

    python3 src/tests/tools/gen_montgomery_asm.py > src/shared/Crypto/MontgomeryAsm.S
    python3 src/tests/tools/gas2masm.py src/shared/Crypto/MontgomeryAsm.S > src/shared/Crypto/MontgomeryAsm.asm

A test regenerates both and compares them with the committed files.
"""
import sys

WIDTHS = (16, 32)

HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
//
// MaNGOS is a full featured server for World of Warcraft, supporting
// the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
//
// Copyright (C) 2005-2026 MaNGOS <https://www.getmangos.eu>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// ---------------------------------------------------------------------------
// The assembly tier of the Montgomery kernel: x86-64, BMI2 + ADX.
// GENERATED by src/tests/tools/gen_montgomery_asm.py; do not edit by hand -- a
// test regenerates it and compares. The generator's docstring explains the shape.
//
//   void mangos_montmul_adx(uint64_t* z, const uint64_t* x, const uint64_t* y,
//                           const uint64_t* m, uint64_t n0inv, uint64_t k);
//     z = x * y * 2^(-64k) mod m, for x, y < m, m odd, k a positive multiple of 4.
//   void mangos_montmul16_adx(z, x, y, m, n0inv), mangos_montmul32_adx(...)
//     the same for k = 16 and k = 32, unrolled.
//   void mangos_montsqr16_adx(uint64_t* z, const uint64_t* x, const uint64_t* m,
//                             uint64_t n0inv), mangos_montsqr32_adx(...)
//     z = x * x * 2^(-64k) mod m, for x < m, m odd.
//   z may alias x or y. Every result is canonical (below m).
//
// CIOS as in the C++ tiers (src/shared/Crypto/Montgomery.cpp): for each limb of x,
// add x_i * y into the accumulator t, then add the multiple of m that clears t[0]
// and drop that limb; after k rounds t is below 2m and one masked subtraction
// makes it canonical. The products from mulx (which leaves the flags alone) feed
// two independent carry chains, adcx on CF for the accumulator and adox on OF for
// the carry between products, so the two additions of every step overlap. In the
// generic procedure nothing inside a chain may touch the flags: pointers and
// counters advance with lea and the loops close with jrcxz, unrolled four limbs
// deep. The unrolled procedures have no loop inside a chain at all.
//
// The squaring forms x * x in a 2k+1-limb accumulator -- the upper triangle by
// rows, doubled by one add-with-carry chain, the diagonal squares by another --
// and reduces it in place, k rows of q_i * m at offset i, each row's carry folded
// into the next row's top limb: 1.5 k^2 products instead of 2 k^2.
//
// Constant-time: the instruction sequence, the loop counts and every address
// depend on k alone; the final subtraction is selected by a mask. Every frame is
// erased before returning.
//
// Register use, all procedures (after the prologue):
//   rdi z   rsi x   r10 y   r11 m   r8 n0inv   rdx multiplier   rax:rbx product
//   r12 carry   r13 zero   r14 the squaring's row carry   rcx, r15 pointers/counters
//   generic: r9 k*8, rbp frame pointer, t[j] at [rsp + 8 + 8j] (a scratch limb at [rsp])
//   unrolled: a fixed frame, t[j] at [rsp + 8 + 8j], the scratch limb at [rsp]
//
// Both ABIs are in this one source under WINDOWS_ABI, each with its unwind
// metadata: CFI for the ELF build, the MASM FRAME directives for ml64 (the
// translator src/tests/tools/gas2masm.py copies the Windows branch through; GAS
// never sees it).
// ---------------------------------------------------------------------------

        .intel_syntax noprefix
        .text
"""

# --------------------------------------------------------------------------- helpers

def t(j):
    """The accumulator limb j of an unrolled frame (t[-1] is the scratch limb)."""
    return f"qword ptr [rsp + {8 + 8 * j}]"


def prologue(name, frame, kind):
    """Pushes, the frame, the argument shuffle. kind: 'mul' (5 args) or 'sqr' (4 args).
    Leaves rdi z, rsi x, r10 y (mul), r11 m, r8 n0inv."""
    o = []
    o.append("        .balign 16")
    o.append(f"        .globl {name}")
    o.append("#if !WINDOWS_ABI")
    o.append(f"        .type {name}, @function")
    o.append("#endif")
    o.append(f"{name}:")
    o.append("#if WINDOWS_ABI")
    for r in ("rbp", "rbx", "r12", "r13", "r14", "r15", "rdi", "rsi"):
        o.append(f"        push {r}")
        o.append(f"        .pushreg {r}")
    o.append(f"        sub rsp, {frame}")
    o.append(f"        .allocstack {frame}")
    o.append("        .endprolog")
    if kind == "mul":
        o.append("        mov rdi, rcx")
        o.append("        mov rsi, rdx")
        o.append("        mov r10, r8")
        o.append("        mov r11, r9")
        o.append(f"        mov r8, qword ptr [rsp + {frame + 104}]")
    else:
        o.append("        mov rdi, rcx")
        o.append("        mov rsi, rdx")
        o.append("        mov r11, r8")
        o.append("        mov r8, r9")
    o.append("#else")
    o.append("        .cfi_startproc")
    for r in ("rbp", "rbx", "r12", "r13", "r14", "r15"):
        o.append(f"        push {r}")
        o.append("        .cfi_adjust_cfa_offset 8")
        o.append(f"        .cfi_rel_offset {r}, 0")
    o.append(f"        sub rsp, {frame}")
    o.append(f"        .cfi_adjust_cfa_offset {frame}")
    if kind == "mul":
        o.append("        mov r10, rdx")
        o.append("        mov r11, rcx")
    else:
        o.append("        mov r11, rdx")
        o.append("        mov r8, rcx")
    o.append("#endif")
    return o


def epilogue(name, frame, tag):
    """Erase the frame, release it, restore, return."""
    o = []
    o.append("        // ---- erase the frame, release it ---------------------------------")
    o.append("        xor eax, eax")
    o.append(f"        mov rcx, {frame}")
    o.append(f".L{tag}_erase:")
    o.append("        sub rcx, 8")
    o.append("        mov qword ptr [rsp + rcx], rax")
    o.append(f"        jnz .L{tag}_erase")
    o.append("        xor edx, edx")
    o.append("        xor r8d, r8d")
    o.append("        xor r12d, r12d")
    o.append("        xor r14d, r14d")
    o.append(f"        add rsp, {frame}")
    o.append("#if WINDOWS_ABI")
    for r in ("rsi", "rdi", "r15", "r14", "r13", "r12", "rbx", "rbp"):
        o.append(f"        pop {r}")
    o.append("        ret")
    o.append("#else")
    o.append(f"        .cfi_adjust_cfa_offset -{frame}")
    for r in ("r15", "r14", "r13", "r12", "rbx", "rbp"):
        o.append(f"        pop {r}")
        o.append("        .cfi_adjust_cfa_offset -8")
    o.append("        ret")
    o.append("        .cfi_endproc")
    o.append(f"        .size {name}, .-{name}")
    o.append("#endif")
    return o


def product(src, acc_in, acc_out):
    """One product step: rdx * [src] added at acc_in, stored at acc_out, carry in r12."""
    return [
        f"        mulx rbx, rax, {src}",
        f"        adcx rax, {acc_in}",
        "        adox rax, r12",
        f"        mov {acc_out}, rax",
        "        mov r12, rbx",
    ]


def final_subtraction(k, top, base):
    """z = t - m kept if top != 0 or no borrow, else z = t. base(j) names t[j]; top names t[k]."""
    o = []
    o.append("        // ---- z = t - m, kept if t[k] != 0 or no borrow; else z = t ----------")
    o.append("        xor r15d, r15d")
    for j in range(k):
        o.append(f"        mov rax, {base(j)}")
        o.append(f"        sbb rax, qword ptr [r11 + {8 * j}]")
        o.append(f"        mov qword ptr [rdi + {8 * j}], rax")
    o.append("        sbb rbx, rbx")
    o.append(f"        mov rax, {top}")
    o.append("        neg rax")
    o.append("        sbb rax, rax")
    o.append("        not rbx")
    o.append("        or rax, rbx")
    o.append("        mov rbx, rax")
    o.append("        not rbx")
    for j in range(k):
        o.append(f"        mov rcx, qword ptr [rdi + {8 * j}]")
        o.append("        and rcx, rax")
        o.append(f"        mov rdx, {base(j)}")
        o.append("        and rdx, rbx")
        o.append("        or rcx, rdx")
        o.append(f"        mov qword ptr [rdi + {8 * j}], rcx")
    return o


# --------------------------------------------------------------------------- montmul, unrolled

def montmul_unrolled(k):
    name = f"mangos_montmul{k}_adx"
    tag = f"mm{k}"
    frame = 8 * (k + 3)          # scratch + t[0 .. k+1]
    o = []
    o.append("")
    o.append(f"// ---- {name}: k = {k}, every loop written out -----------------------------")
    o += prologue(name, frame, "mul")
    o.append("        // t[0 .. k+1] = 0")
    o.append("        xor eax, eax")
    for j in range(k + 2):
        o.append(f"        mov {t(j)}, rax")
    o.append("        xor r13d, r13d")
    o.append("        mov rcx, rsi")
    o.append(f"        lea r15, [rsi + {8 * k}]")
    o.append(f".L{tag}_pass:")
    o.append("        // ---- t += x[i] * y ------------------------------------------------")
    o.append("        mov rdx, qword ptr [rcx]")
    o.append("        xor r12d, r12d")
    for j in range(k):
        o += product(f"qword ptr [r10 + {8 * j}]", t(j), t(j))
    o.append("        // t[k] += carry + CF + OF; t[k+1] = what overflows")
    o.append(f"        mov rax, {t(k)}")
    o.append("        adcx rax, r12")
    o.append("        adox rax, r13")
    o.append(f"        mov {t(k)}, rax")
    o.append("        mov rax, r13")
    o.append("        adcx rax, r13")
    o.append("        adox rax, r13")
    o.append(f"        mov {t(k + 1)}, rax")
    o.append("        // ---- t = (t + u * m) / 2^64, u = t[0] * n0inv --------------------")
    o.append(f"        mov rdx, {t(0)}")
    o.append("        imul rdx, r8")
    o.append("        xor r12d, r12d")
    for j in range(k):
        o += product(f"qword ptr [r11 + {8 * j}]", t(j), t(j - 1))
    o.append("        // t[k-1] = t[k] + carry + CF + OF; t[k] = t[k+1] + what overflows")
    o.append(f"        mov rax, {t(k)}")
    o.append("        adcx rax, r12")
    o.append("        adox rax, r13")
    o.append(f"        mov {t(k - 1)}, rax")
    o.append(f"        mov rax, {t(k + 1)}")
    o.append("        adcx rax, r13")
    o.append("        adox rax, r13")
    o.append(f"        mov {t(k)}, rax")
    o.append("        lea rcx, [rcx + 8]")
    o.append("        cmp rcx, r15")
    o.append(f"        jb .L{tag}_pass")
    o += final_subtraction(k, t(k), t)
    o += epilogue(name, frame, tag)
    return o


# --------------------------------------------------------------------------- montsqr, unrolled

def montsqr_unrolled(k):
    name = f"mangos_montsqr{k}_adx"
    tag = f"ms{k}"
    frame = 8 * (2 * k + 2)      # scratch + t[0 .. 2k]
    o = []
    o.append("")
    o.append(f"// ---- {name}: k = {k}; the triangle, doubled, plus the diagonal; then in-place reduction")
    o += prologue(name, frame, "sqr")
    o.append("        // t[0 .. 2k] = 0")
    o.append("        xor eax, eax")
    for j in range(2 * k + 1):
        o.append(f"        mov {t(j)}, rax")
    o.append("        xor r13d, r13d")
    o.append("        // ---- the upper triangle: for i, t += x[i] * x[i+1 ..] at offset i -----")
    for i in range(k - 1):
        o.append(f"        mov rdx, qword ptr [rsi + {8 * i}]")
        o.append("        xor r12d, r12d")
        for j in range(i + 1, k):
            o += product(f"qword ptr [rsi + {8 * j}]", t(i + j), t(i + j))
        # position i + k was untouched so far: the last carry, plus both chain carries
        o.append("        adcx r12, r13")
        o.append("        adox r12, r13")
        o.append(f"        mov {t(i + k)}, r12")
    o.append("        // ---- t = 2t: one add-with-carry chain over the 2k limbs --------------")
    o.append("        xor eax, eax")
    for p in range(2 * k):
        o.append(f"        mov rax, {t(p)}")
        o.append("        adc rax, rax")
        o.append(f"        mov {t(p)}, rax")
    o.append("        // ---- t += x[i]^2 at offset 2i: one chain, each limb visited once ------")
    o.append("        xor r12d, r12d")
    for i in range(k):
        o.append(f"        mov rdx, qword ptr [rsi + {8 * i}]")
        o.append("        mulx rbx, rax, rdx")
        o.append(f"        adcx rax, {t(2 * i)}")
        o.append(f"        mov {t(2 * i)}, rax")
        o.append(f"        adcx rbx, {t(2 * i + 1)}")
        o.append(f"        mov {t(2 * i + 1)}, rbx")
    o.append("        // ---- reduce in place: row i adds q_i * m at offset i, q_i = t[i] * n0inv;")
    o.append("        // the carry out of a row is folded into the next row's top limb (r14)")
    o.append("        xor r14d, r14d")
    o.append("        lea rbp, [rsp + 8]")
    o.append(f"        mov rcx, {k}")
    o.append(f".L{tag}_row:")
    o.append("        mov rdx, qword ptr [rbp]")
    o.append("        imul rdx, r8")
    o.append("        xor r12d, r12d")
    for j in range(k):
        o += product(f"qword ptr [r11 + {8 * j}]", f"qword ptr [rbp + {8 * j}]", f"qword ptr [rbp + {8 * j}]")
    o.append(f"        mov rax, qword ptr [rbp + {8 * k}]")
    o.append("        adcx rax, r12")
    o.append("        adox rax, r14")
    o.append(f"        mov qword ptr [rbp + {8 * k}], rax")
    o.append("        mov r14, r13")
    o.append("        adcx r14, r13")
    o.append("        adox r14, r13")
    o.append("        lea rbp, [rbp + 8]")
    o.append("        sub rcx, 1")
    o.append(f"        jnz .L{tag}_row")
    o.append(f"        mov {t(2 * k)}, r14")
    o += final_subtraction(k, t(2 * k), lambda j: t(k + j))
    o += epilogue(name, frame, tag)
    return o


# --------------------------------------------------------------------------- montmul, generic k

GENERIC = r"""
// ---- mangos_montmul_adx: generic k, a multiple of 4; loops, flag-neutral inside the chains
        .balign 16
        .globl mangos_montmul_adx
#if !WINDOWS_ABI
        .type mangos_montmul_adx, @function
#endif
mangos_montmul_adx:
#if WINDOWS_ABI
        push rbp
        .pushreg rbp
        push rbx
        .pushreg rbx
        push r12
        .pushreg r12
        push r13
        .pushreg r13
        push r14
        .pushreg r14
        push r15
        .pushreg r15
        push rdi
        .pushreg rdi
        push rsi
        .pushreg rsi
        mov rbp, rsp
        .setframe rbp, 0
        .endprolog
        mov rdi, rcx
        mov rsi, rdx
        mov r10, r8
        mov r11, r9
        mov r8, qword ptr [rbp + 104]
        mov r9, qword ptr [rbp + 112]
#else
        .cfi_startproc
        push rbp
        .cfi_adjust_cfa_offset 8
        .cfi_rel_offset rbp, 0
        push rbx
        .cfi_adjust_cfa_offset 8
        .cfi_rel_offset rbx, 0
        push r12
        .cfi_adjust_cfa_offset 8
        .cfi_rel_offset r12, 0
        push r13
        .cfi_adjust_cfa_offset 8
        .cfi_rel_offset r13, 0
        push r14
        .cfi_adjust_cfa_offset 8
        .cfi_rel_offset r14, 0
        push r15
        .cfi_adjust_cfa_offset 8
        .cfi_rel_offset r15, 0
        mov rbp, rsp
        .cfi_def_cfa_register rbp
        mov r10, rdx
        mov r11, rcx
#endif
        shl r9, 3
        xor r13d, r13d

        // frame: scratch (8) + t[0 .. k+1] ((k+2)*8), rounded up to 16, plus 8 so
        // that rsp -- 8 mod 16 after the pushes in both ABIs -- is aligned inside
        lea rax, [r9 + 39]
        and rax, -16
        add rax, 8
        sub rsp, rax

        // t[0 .. k+1] = 0
        xor eax, eax
        lea rcx, [r9 + 16]
.Lzero:
        mov qword ptr [rsp + rcx], rax
        sub rcx, 8
        jnz .Lzero

        xor r14d, r14d
.Lrow:
        // ---- t += x[i] * y ------------------------------------------------
        mov rdx, qword ptr [rsi + r14]
        mov rcx, r9
        shr rcx, 5
        xor r15d, r15d
        xor r12d, r12d
.Lrow1:
        jrcxz .Lrow1_done
        mulx rbx, rax, qword ptr [r10 + r15]
        adcx rax, qword ptr [rsp + r15 + 8]
        adox rax, r12
        mov qword ptr [rsp + r15 + 8], rax
        mov r12, rbx
        mulx rbx, rax, qword ptr [r10 + r15 + 8]
        adcx rax, qword ptr [rsp + r15 + 16]
        adox rax, r12
        mov qword ptr [rsp + r15 + 16], rax
        mov r12, rbx
        mulx rbx, rax, qword ptr [r10 + r15 + 16]
        adcx rax, qword ptr [rsp + r15 + 24]
        adox rax, r12
        mov qword ptr [rsp + r15 + 24], rax
        mov r12, rbx
        mulx rbx, rax, qword ptr [r10 + r15 + 24]
        adcx rax, qword ptr [rsp + r15 + 32]
        adox rax, r12
        mov qword ptr [rsp + r15 + 32], rax
        mov r12, rbx
        lea r15, [r15 + 32]
        lea rcx, [rcx - 1]
        jmp .Lrow1
.Lrow1_done:
        // t[k] += carry + CF + OF; t[k+1] = what overflows
        mov rax, qword ptr [rsp + r9 + 8]
        adcx rax, r12
        adox rax, r13
        mov qword ptr [rsp + r9 + 8], rax
        mov rax, r13
        adcx rax, r13
        adox rax, r13
        mov qword ptr [rsp + r9 + 16], rax

        // ---- t = (t + u * m) / 2^64, u = t[0] * n0inv --------------------
        mov rdx, qword ptr [rsp + 8]
        imul rdx, r8
        mov rcx, r9
        shr rcx, 5
        xor r15d, r15d
        xor r12d, r12d
.Lrow2:
        jrcxz .Lrow2_done
        mulx rbx, rax, qword ptr [r11 + r15]
        adcx rax, qword ptr [rsp + r15 + 8]
        adox rax, r12
        mov qword ptr [rsp + r15], rax
        mov r12, rbx
        mulx rbx, rax, qword ptr [r11 + r15 + 8]
        adcx rax, qword ptr [rsp + r15 + 16]
        adox rax, r12
        mov qword ptr [rsp + r15 + 8], rax
        mov r12, rbx
        mulx rbx, rax, qword ptr [r11 + r15 + 16]
        adcx rax, qword ptr [rsp + r15 + 24]
        adox rax, r12
        mov qword ptr [rsp + r15 + 16], rax
        mov r12, rbx
        mulx rbx, rax, qword ptr [r11 + r15 + 24]
        adcx rax, qword ptr [rsp + r15 + 32]
        adox rax, r12
        mov qword ptr [rsp + r15 + 24], rax
        mov r12, rbx
        lea r15, [r15 + 32]
        lea rcx, [rcx - 1]
        jmp .Lrow2
.Lrow2_done:
        // t[k-1] = t[k] + carry + CF + OF; t[k] = t[k+1] + what overflows
        mov rax, qword ptr [rsp + r9 + 8]
        adcx rax, r12
        adox rax, r13
        mov qword ptr [rsp + r9], rax
        mov rax, qword ptr [rsp + r9 + 16]
        adcx rax, r13
        adox rax, r13
        mov qword ptr [rsp + r9 + 8], rax

        lea r14, [r14 + 8]
        cmp r14, r9
        jb .Lrow

        // ---- z = t - m, kept if t[k] != 0 or no borrow; else z = t ----------
        mov rcx, r9
        shr rcx, 5
        xor r15d, r15d
.Lsub:
        jrcxz .Lsub_done
        mov rax, qword ptr [rsp + r15 + 8]
        sbb rax, qword ptr [r11 + r15]
        mov qword ptr [rdi + r15], rax
        mov rax, qword ptr [rsp + r15 + 16]
        sbb rax, qword ptr [r11 + r15 + 8]
        mov qword ptr [rdi + r15 + 8], rax
        mov rax, qword ptr [rsp + r15 + 24]
        sbb rax, qword ptr [r11 + r15 + 16]
        mov qword ptr [rdi + r15 + 16], rax
        mov rax, qword ptr [rsp + r15 + 32]
        sbb rax, qword ptr [r11 + r15 + 24]
        mov qword ptr [rdi + r15 + 24], rax
        lea r15, [r15 + 32]
        lea rcx, [rcx - 1]
        jmp .Lsub
.Lsub_done:
        sbb rbx, rbx
        mov rax, qword ptr [rsp + r9 + 8]
        neg rax
        sbb rax, rax
        not rbx
        or rax, rbx
        mov rbx, rax
        not rbx
        xor r15d, r15d
.Lblend:
        mov rcx, qword ptr [rdi + r15]
        and rcx, rax
        mov rdx, qword ptr [rsp + r15 + 8]
        and rdx, rbx
        or rcx, rdx
        mov qword ptr [rdi + r15], rcx
        add r15, 8
        cmp r15, r9
        jb .Lblend

        // ---- erase the accumulator, release the frame ----------------------
        xor eax, eax
        lea rcx, [r9 + 16]
.Lerase:
        mov qword ptr [rsp + rcx], rax
        sub rcx, 8
        jnz .Lerase
        mov qword ptr [rsp], rax
        lea rsp, [rbp]
#if WINDOWS_ABI
        pop rsi
        pop rdi
        pop r15
        pop r14
        pop r13
        pop r12
        pop rbx
        pop rbp
        ret
#else
        .cfi_def_cfa_register rsp
        pop r15
        .cfi_adjust_cfa_offset -8
        pop r14
        .cfi_adjust_cfa_offset -8
        pop r13
        .cfi_adjust_cfa_offset -8
        pop r12
        .cfi_adjust_cfa_offset -8
        pop rbx
        .cfi_adjust_cfa_offset -8
        pop rbp
        .cfi_adjust_cfa_offset -8
        ret
        .cfi_endproc
        .size mangos_montmul_adx, .-mangos_montmul_adx
#endif
"""


def generate():
    lines = [HEADER.rstrip("\n")]
    lines.append(GENERIC.rstrip("\n"))
    for k in WIDTHS:
        lines += montmul_unrolled(k)
    for k in WIDTHS:
        lines += montsqr_unrolled(k)
    lines.append("#if !WINDOWS_ABI")
    lines.append('        .section .note.GNU-stack,"",@progbits')
    lines.append("#endif")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.stdout.write(generate())
