#!/usr/bin/env python3
"""Generate src/tests/BigIntVectors.h: big-integer test vectors computed by Python.

Python's integers are the second, independent reference for the in-house BigInt and
Montgomery code (the first is what OpenSSL produced through the old wrappers, in
CryptoGoldenVectors.h; the third, on Linux, is s2n-bignum). Seeded, so the table is
reproducible: python3 src/tests/tools/gen_bigint_vectors.py > src/tests/BigIntVectors.h
"""
import random

R = random.Random(0x4D414E474F53)
ONES = (1 << 64) - 1


def rnd(bits):
    """A random value of exactly `bits` bits (top bit set)."""
    return R.getrandbits(bits) | (1 << (bits - 1))


def odd(bits):
    return rnd(bits) | 1


def limbs(*words):
    """A value from little-endian 64-bit limbs."""
    v = 0
    for i, w in enumerate(words):
        v |= w << (64 * i)
    return v


def hexs(v):
    """Uppercase, whole bytes, no leading zero bytes -- the BN_bn2hex shape BigInt::ToHex keeps."""
    if v == 0:
        return "0"
    h = format(v, "X")
    return ("0" + h) if len(h) % 2 else h


out = []
out.append("// Generated by src/tests/tools/gen_bigint_vectors.py (seed 0x4D414E474F53); do not edit by hand.")
out.append("// Python's integers are the reference here: pow(), *, divmod(), pow(x, -1, m).")
out.append("#ifndef MANGOS_H_TESTS_BIGINT_VECTORS")
out.append("#define MANGOS_H_TESTS_BIGINT_VECTORS")
out.append("")
out.append("namespace vectors")
out.append("{")

# ---------------------------------------------------------------- modular exponentiation
out.append("    /// base^exp mod m (uppercase minimal hex). Bases narrower than, equal to and wider than the modulus;")
out.append("    /// exponents of the modulus width, e = 65537, e = 1, e = 0; moduli odd, 256/1024/2048 bits.")
out.append("    struct ModExpVector { const char* base; const char* exp; const char* mod; const char* result; };")
out.append("    inline const ModExpVector kModExp[] = {")
for mod_bits in (256, 1024, 2048):
    m = odd(mod_bits)
    for base_bits in (mod_bits // 2, mod_bits - 1, mod_bits, 2 * mod_bits, 4096):
        base = rnd(base_bits)
        for e in (rnd(mod_bits), 65537, 1, 0):
            out.append('    {"%s", "%s", "%s", "%s"},' % (hexs(base), hexs(e), hexs(m), hexs(pow(base, e, m))))
    # the Montgomery edge patterns for this modulus
    for base in (m - 1, 1, 0, m + 1, limbs(*([ONES] * (mod_bits // 64)))):
        e = rnd(mod_bits)
        out.append('    {"%s", "%s", "%s", "%s"},' % (hexs(base), hexs(e), hexs(m), hexs(pow(base, e, m))))
# a modulus whose top limb is 0x8000000000000000, and one whose top limb is 1 (short top limb)
for mod_bits in (256, 1024):
    top = [R.getrandbits(64) for _ in range(mod_bits // 64)]
    top[0] |= 1
    top[-1] = 1 << 63
    m = limbs(*top)
    for base in (rnd(mod_bits), m - 1, m - 2):
        e = rnd(mod_bits)
        out.append('    {"%s", "%s", "%s", "%s"},' % (hexs(base), hexs(e), hexs(m), hexs(pow(base, e, m))))
    low = [R.getrandbits(64) for _ in range(mod_bits // 64)]
    low[0] |= 1
    low[-1] = 1
    m = limbs(*low)
    base, e = rnd(mod_bits), rnd(mod_bits)
    out.append('    {"%s", "%s", "%s", "%s"},' % (hexs(base), hexs(e), hexs(m), hexs(pow(base, e, m))))
# even and single-limb moduli: the plain path
for m in (rnd(256) & ~1, rnd(200) & ~1, 0xFFFFFFFFFFFFFFFF, 0x8000000000000001, 3, 2, 1):
    base = rnd(300)
    e = rnd(160)
    out.append('    {"%s", "%s", "%s", "%s"},' % (hexs(base), hexs(e), hexs(m), hexs(pow(base, e, m))))
out.append("    };")
out.append("")

# ---------------------------------------------------------------- multiplication
out.append("    struct MulVector { const char* a; const char* b; const char* product; };")
out.append("    inline const MulVector kMul[] = {")
for a_bits, b_bits in ((64, 64), (65, 63), (128, 128), (256, 152), (320, 256), (1024, 1024), (2048, 2048), (4096, 64), (1, 4096), (100, 3)):
    a, b = rnd(a_bits), rnd(b_bits)
    out.append('    {"%s", "%s", "%s"},' % (hexs(a), hexs(b), hexs(a * b)))
for a, b in ((ONES, ONES), (limbs(ONES, ONES), limbs(ONES, ONES)), (limbs(ONES, ONES, ONES, ONES), ONES), (0, rnd(256)), (rnd(256), 0), (1, rnd(2048)), (limbs(0, 1), limbs(0, 1))):
    out.append('    {"%s", "%s", "%s"},' % (hexs(a), hexs(b), hexs(a * b)))
out.append("    };")
out.append("")

# ---------------------------------------------------------------- division
out.append("    /// a = q * d + r, 0 <= r < d.")
out.append("    struct DivVector { const char* a; const char* d; const char* q; const char* r; };")
out.append("    inline const DivVector kDiv[] = {")
cases = []
for a_bits, d_bits in ((128, 64), (192, 128), (256, 256), (320, 256), (512, 256), (1024, 1024), (2048, 1024), (4096, 2048), (4096, 65), (100, 99)):
    cases.append((rnd(a_bits), rnd(d_bits)))
# Knuth D corner cases on 64-bit limbs: qhat one/two too large, the add-back, the un == vn1 estimate
cases += [
    (limbs(0, 0, 1 << 63), limbs(1, 1 << 63)),
    (limbs(ONES, ONES, (1 << 63) - 1), limbs(1, 1 << 63)),
    (limbs(0, ONES - 1, 1 << 63), limbs(ONES, 1 << 63)),
    (limbs(3, 0, 1 << 63), limbs(1, 1 << 61)),
    (limbs(0, 0, 0, 1 << 63), limbs(0, 1 << 63)),
    (limbs(ONES, ONES, ONES, ONES), limbs(ONES, ONES)),
    (limbs(ONES, ONES, ONES, ONES), limbs(1, 1)),
    (limbs(0, 0, ONES, ONES), limbs(ONES, ONES)),
    (limbs(1, 0, 1 << 63, 1 << 63), limbs(1 << 63, 1 << 63)),
    (limbs(0, 1 << 63, ONES, 1 << 63), limbs(1, 1 << 63)),
    (limbs(*([ONES] * 8)), limbs(*([ONES] * 4))),
    (limbs(*([ONES] * 8)), limbs(*([1 << 63] * 4))),
]
# dividend smaller, equal, one more, one less; single-limb divisors; exact multiples
d = rnd(256)
cases += [(d - 1, d), (d, d), (d + 1, d), (0, d), (rnd(512), 1), (rnd(512), 2), (rnd(512), ONES), (rnd(512), 1 << 63), (rnd(512), 10000000000000000000)]
for _ in range(6):
    dd, qq = rnd(64 * R.randint(1, 4)), rnd(32 * R.randint(1, 8))
    cases.append((dd * qq, dd))
for a, dv in cases:
    q, r = divmod(a, dv)
    out.append('    {"%s", "%s", "%s", "%s"},' % (hexs(a), hexs(dv), hexs(q), hexs(r)))
out.append("    };")
out.append("")

# ---------------------------------------------------------------- modular inverse
out.append("    /// inv = a^-1 mod m, or 0 when gcd(a, m) != 1.")
out.append("    struct InvVector { const char* a; const char* m; const char* inv; };")
out.append("    inline const InvVector kInv[] = {")
import math
inv_cases = []
for m_bits in (64, 256, 1024, 2048):
    m = odd(m_bits)
    for _ in range(3):
        a = R.randrange(1, m)
        inv_cases.append((a, m))
    inv_cases.append((1, m))
    inv_cases.append((m - 1, m))
# even modulus, and no inverse
inv_cases += [(3, 16), (5, 1 << 64), (6, 9), (limbs(0, 1), odd(256)), (odd(256), limbs(0, 1))]
for a, m in inv_cases:
    inv = pow(a, -1, m) if math.gcd(a, m) == 1 else 0
    out.append('    {"%s", "%s", "%s"},' % (hexs(a), hexs(m), hexs(inv)))
out.append("    };")
out.append("")

# ---------------------------------------------------------------- decimal rendering
out.append("    struct DecVector { const char* hex; const char* decimal; };")
out.append("    inline const DecVector kDecimal[] = {")
for v in (0, 1, 9, 10, (1 << 64) - 1, 1 << 64, 10 ** 19, 10 ** 19 - 1, 10 ** 19 + 1, rnd(200), rnd(2048)):
    out.append('    {"%s", "%d"},' % (hexs(v), v))
out.append("    };")
out.append("}")
out.append("")
out.append("#endif")
print("\n".join(out))
