#!/usr/bin/env python3
"""Generate src/tests/PrimeVectors.h: primality verdicts computed by Python.

Python has no primality test in its standard library, so the reference is a
Miller-Rabin with 40 fixed bases written here (a composite that survives 40 bases
is astronomically unlikely, and for the numbers below 3.3e24 the first 12 prime
bases are a deterministic test). Seeded, so the table is reproducible:
python3 src/tests/tools/gen_prime_vectors.py > src/tests/PrimeVectors.h
"""
import random

R = random.Random(0x5052494D45)   # "PRIME"
FIRST_PRIMES = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173]


def is_probable_prime(n):
    if n < 2:
        return False
    for p in FIRST_PRIMES:
        if n % p == 0:
            return n == p
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in FIRST_PRIMES:
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def hexs(v):
    h = format(v, "X")
    return ("0" + h) if len(h) % 2 else h


def random_prime(bits):
    while True:
        c = R.getrandbits(bits) | (1 << (bits - 1)) | 1
        if is_probable_prime(c):
            return c


out = []
out.append("// Generated by src/tests/tools/gen_prime_vectors.py (seed 0x5052494D45); do not edit by hand.")
out.append("#ifndef MANGOS_H_TESTS_PRIME_VECTORS")
out.append("#define MANGOS_H_TESTS_PRIME_VECTORS")
out.append("")
out.append("namespace vectors")
out.append("{")
out.append("    /// n (uppercase hex) and whether it is prime.")
out.append("    struct PrimeVector { const char* n; bool prime; };")
out.append("    inline const PrimeVector kPrimality[] = {")
cases = []
# the classics: strong pseudoprimes to base 2, Carmichael numbers, Mersenne primes, and small primes/composites
for n in (2047, 3277, 4033, 4681, 8321, 15841, 29341, 42799, 49141, 52633):
    cases.append(n)
for n in (561, 1105, 1729, 2465, 2821, 6601, 8911, 41041, 62745, 63973):
    cases.append(n)
for e in (31, 61, 89, 107, 127, 521, 607):
    cases.append((1 << e) - 1)
for n in (5, 7, 9, 15, 17, 25, 27, 49, 65537, 65539, 65541, 4294967291, 4294967297, 18446744073709551557, 18446744073709551615):
    cases.append(n)
# random odd numbers and random primes at 256, 512 and 1024 bits
for bits in (256, 512, 1024):
    for _ in range(6):
        cases.append(R.getrandbits(bits) | (1 << (bits - 1)) | 1)
    for _ in range(4):
        cases.append(random_prime(bits))
# products of two primes (the RSA shape) and a prime times a small factor
for bits in (256, 512):
    p, q = random_prime(bits), random_prime(bits)
    cases.append(p * q)
    cases.append(p * 3)
    cases.append(p * p)
for n in cases:
    out.append('    {"%s", %s},' % (hexs(n), "true" if is_probable_prime(n) else "false"))
out.append("    };")
out.append("")
out.append("    /// Every odd n below 2^16 that has no prime factor below 2^16 other than itself -- i.e. the odd primes")
out.append("    /// below 2^16 -- as a count, and the odd numbers below 10000 that pass the small-prime sieve, as a bitmap")
out.append("    /// (bit i set when 2i + 1 passes).")
primes_below = [n for n in range(3, 65536, 2) if is_probable_prime(n)]
out.append("    inline const unsigned kOddPrimesBelow65536 = %d;" % len(primes_below))
bitmap = []
for i in range(5000):
    n = 2 * i + 1
    bitmap.append(1 if (n > 1 and is_probable_prime(n)) else 0)
words = []
for w in range(0, 5000, 32):
    v = 0
    for b in range(32):
        if w + b < 5000 and bitmap[w + b]:
            v |= 1 << b
    words.append("0x%08Xu" % v)
out.append("    inline const unsigned kSievePassBits[%d] = {" % len(words))
for i in range(0, len(words), 8):
    out.append("        " + ", ".join(words[i:i + 8]) + ",")
out.append("    };")
out.append("}")
out.append("")
out.append("#endif")
print("\n".join(out))
