name: Codestyle Checks

permissions:
  contents: read

on:
  push:
    branches: [master, united, devel]
  pull_request:
    branches: [master, united, devel]

concurrency:
  group: codestyle-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Check Codestyling
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Check Codestyling
        run: source ./.github/apps/ci/ci-codestyle.sh
